data_dir: data/trashnet
classes:
  - battery
  - biological
  - brown-glass
  - cardboard
  - clothes
  - green-glass
  - metal
  - paper
  - plastic
  - shoes
  - trash
  - white-glass
model: baseline_cnn
batch_size: 32
img_size: 224
augment: true
checkpoint_dir: outputs
log_dir: runs/baseline_cnn
checkpoint_path: outputs/trash_classifier.pth
