data_dir: data/trashnet
classes: [metal, plastic, paper, glass, cardboard, trash, organic, medical]
level_1_classes: [Organic, Inorganic]
level_2_classes: [metal, plastic, paper, glass, cardboard, trash, organic, medical]
hierarchy:
  metal: Inorganic
  plastic: Inorganic
  paper: Inorganic
  glass: Inorganic
  cardboard: Inorganic
  medical: Inorganic
  trash: Organic
  organic: Organic
model: baseline_cnn
batch_size: 32
img_size: 224
epochs: 1
lr: 0.001
augment: true
pretrained: false
checkpoint_dir: outputs
log_dir: runs/baseline_cnn
